### PR TITLE
Retry on snap installation failures

### PR DESCRIPTION
**Pull request by lourot**
Fix for https://bugs.launchpad.net/layer-snap/+bug/1839616

Also made the linter happy.

### CODE REVIEW

**Comment by lourot** [comment]
CI validation here: https://review.opendev.org/745677

**Comment by lourot** [comment]
Also let me know if I should create the review here instead: https://git.launchpad.net/layer-snap

**Comment by stub42** [comment]
Do we know if this actually helps? I had assumed retry behavior would be baked into snapd, like it is with other package management tools such as apt. Rather than relying on all the clients such as the snap CLI or 'software stores' to second guess its behavior.

**Comment by lourot** [comment]
I heard several times (e.g. from @chrismacnaughton) that when we end up with a non-installed core snap because of some network hiccup at deployment, `_install_store()` raises, the unit is in error state, and actually retrying the hook (`juju resolved`) gets us up and running again. That's why we think this will help in some cases.

**Comment by ChrisMacNaughton** [comment]
In offline discussion on the [linked bug](https://bugs.launchpad.net/layer-snap/+bug/1839616), it was determined that retries resolved those issues, although they are _not_ a guarantee of success. The most correct solution is actually for Juju to modify the lxd settings mentioned on that bug to ensure that installs don't run into this error.

**Comment by lourot** [comment]
I think the linked bug covers two classes of cases:
- the bug was originally opened on cases where network hiccups were the root cause: for this I think this patch is good;
- the last case in the bug which dragged a lot of attention is more "for Juju to modify the lxd settings mentioned" as @ChrisMacNaughton just wrote.

**Review by stub42 — APPROVED** [review]
Code all looks good. The new dependency should not be a problem, as charmtools will handle that. If the changed behavior is problematic in cases, then we can make it configurable per charm via layer.yaml

**Comment by stub42** [comment]
PR is listed as 'work in progress', so github isn't going to let me merge it.

**Comment by lourot** [comment]
@stub42 done, thanks!

**Comment by stub42** [comment]
I'm told snapd will retry when failures occur during downloading, but as we are more concerned with initial handshaking this change seems useful.

**Pull request merged**
