### PR TITLE
Print subprocess output when snap install fails

### PR DESCRIPTION
**Pull request by Cynerva**
Proposal to fix https://bugs.launchpad.net/layer-snap/+bug/1838274

I haven't tested this yet. Will follow up once I have.

### CODE REVIEW

**Comment by Cynerva** [comment]
Tested the four cases below. Output isn't pretty, but it's readable.

_install_store success:
```
unit-test-0: 10:21:01 INFO unit.test/0.juju-log Installing kubectl from store
unit-test-0: 10:21:04 DEBUG unit.test/0.juju-log tracer: set flag snap.installed.kubectl
```

_install_store failure:
```
unit-test-0: 10:20:25 INFO unit.test/0.juju-log Installing kubectl from store
unit-test-0: 10:20:25 ERROR unit.test/0.juju-log Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-0/.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 73, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-test-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-test-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-test-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-test-0/charm/reactive/test.py", line 10, in install
    snap.install('kubectl', channel=channel, classic=True)
  File "lib/charms/layer/snap.py", line 53, in install
    _install_store(snapname, **kw)
  File "lib/charms/layer/snap.py", line 304, in _install_store
    out = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['snap', 'install', '--channel=nonsense', '--classic', 'kubectl']' returned non-zero exit status 1

unit-test-0: 10:20:25 DEBUG unit.test/0.install b'error: snap "kubectl" is not available on nonsense/stable but is available to\n       install on the following tracks:\n\n       latest/stable  snap install --stable kubectl\n       1.15/stable    snap install --channel=1.15 kubectl\n       1.14/stable    snap install --channel=1.14 kubectl\n       1.13/stable    snap install --channel=1.13 kubectl\n       1.12/stable    snap install --channel=1.12 kubectl\n       1.11/stable    snap install --channel=1.11 kubectl\n       1.10/stable    snap install --channel=1.10 kubectl\n       1.9/stable     snap install --channel=1.9 kubectl\n       1.8/stable     snap install --channel=1.8 kubectl\n       1.7/stable     snap install --channel=1.7 kubectl\n       1.6/stable     snap install --channel=1.6 kubectl\n       1.5/stable     snap install --channel=1.5 kubectl\n\n       Please be mindful that different tracks may include different features.\n       Get more information with \'snap info kubectl\'.\n'
```

_refresh_store success:
```
unit-test-0: 10:21:05 INFO unit.test/0.juju-log Refreshing kubectl from store
unit-test-0: 10:21:06 DEBUG unit.test/0.leader-elected b'snap "kubectl" has no updates available\n'
```

_refresh_store failure:
```
unit-test-0: 10:22:05 INFO unit.test/0.juju-log Refreshing kubectl from store
unit-test-0: 10:22:06 ERROR unit.test/0.juju-log Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-0/.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 73, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-test-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-test-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-test-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-test-0/charm/reactive/test.py", line 10, in install
    snap.install('kubectl', channel=channel, classic=True)
  File "lib/charms/layer/snap.py", line 48, in install
    refresh(snapname, **kw)
  File "lib/charms/layer/snap.py", line 89, in refresh
    _refresh_store(snapname, **kw)
  File "lib/charms/layer/snap.py", line 321, in _refresh_store
    out = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['snap', 'refresh', '--amend', '--channel=nonsense', '--classic', 'kubectl']' returned non-zero exit status 1

unit-test-0: 10:22:06 DEBUG unit.test/0.config-changed b'error: snap "kubectl" is not available on nonsense/stable but is available to\n       install on the following tracks:\n\n       latest/stable  snap refresh --stable kubectl\n       1.15/stable    snap refresh --channel=1.15 kubectl\n       1.14/stable    snap refresh --channel=1.14 kubectl\n       1.13/stable    snap refresh --channel=1.13 kubectl\n       1.12/stable    snap refresh --channel=1.12 kubectl\n       1.11/stable    snap refresh --channel=1.11 kubectl\n       1.10/stable    snap refresh --channel=1.10 kubectl\n       1.9/stable     snap refresh --channel=1.9 kubectl\n       1.8/stable     snap refresh --channel=1.8 kubectl\n       1.7/stable     snap refresh --channel=1.7 kubectl\n       1.6/stable     snap refresh --channel=1.6 kubectl\n       1.5/stable     snap refresh --channel=1.5 kubectl\n\n       Please be mindful that different tracks may include different features.\n       Get more information with \'snap info kubectl\'.\n'
```

**Comment by jhobbs** [comment]
This worked for me too and let me figure out my config issue:

2019-07-30 15:44:23 DEBUG install b'snap "core" is already installed, see \'snap help refresh\'\n'
2019-07-30 15:44:23 DEBUG install b'error: cannot install "prometheus": cannot get nonce from store: Post\n       https://api.snapcraft.io/api/v1/snaps/auth/nonces: proxyconnect tcp:\n       dial tcp: lookup squid.internal: no such host\n'

+1

**Review by jhobbs — APPROVED** [review]
LGTM and worked in my testing.

**Comment by stub42** [comment]
Changes landed with https://code.launchpad.net/~fnordahl/layer-snap/+git/layer-snap/+merge/371125

**Comment by stub42** [comment]
Reopening as this branch tackles refresh as well as install. Landed branch just handles install.

**Pull request closed without merging**
